changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
    - title: New Features 🎉
      labels:
        - minor
    - title: Fixes
      labels:
        - patch
    - title: Other Changes
      labels:
        - "*"
