changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
<<<<<<< HEAD
        - major
    - title: New Features 🎉
=======
        - breaking
    - title: Exciting New Features 🎉
>>>>>>> 18d4dd8 (InitialVersion)
      labels:
        - minor
    - title: Fixes
      labels:
        - patch
    - title: Other Changes
      labels:
        - "*"
