#
# Module manifest for module 'Indented.ScriptAnalyzerRules'
#
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
# Generated by: Chris Dent
#
# Generated on: 26/07/17
========
# Module manifest for module 'InfrastructureAsCode'
#
# Generated by: Dylan Prins
#
# Generated on: 8/23/2022
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1
#

@{

    # Script module or binary module file associated with this manifest.
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    RootModule           = 'Indented.ScriptAnalyzerRules.psm1'

    # Version number of this module.
    ModuleVersion        = '1.1.0'
========
    RootModule        = 'InSpark.InfrastructureAsCode.psm1'

    # Version number of this module.
    ModuleVersion     = '6.1.3'
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

    # Supported PSEditions
    CompatiblePSEditions = @('Desktop', 'Core')

    # ID used to uniquely identify this module
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    GUID                 = '402f8a00-9879-468b-aba0-7d204869aade'

    # Author of this module
    Author               = 'Chris Dent'

    # Company or vendor of this module
    CompanyName          = 'Chris Dent'

    # Copyright statement for this module
    Copyright            = '(c) 2017 Chris Dent. All rights reserved.'

    # Description of the functionality provided by this module
    Description          = 'Extra rules for PSScriptAnalyzer.'
========
    GUID              = 'b9f88665-969d-4670-849a-407cfc372831'

    # Author of this module
    Author            = 'Dylan Prins'

    # Company or vendor of this module
    CompanyName       = 'Unknown'

    # Copyright statement for this module
    Copyright         = '(c) Dylan Prins. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'Powershell module for API to DevOps services'
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion    = '5.1'

    # Name of the Windows PowerShell host required by this module
    # PowerShellHostName = ''

    # Minimum version of the Windows PowerShell host required by this module
    # PowerShellHostVersion = '5.0'

    # Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # DotNetFrameworkVersion = ''

    # Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
    # CLRVersion = ''

    # Processor architecture (None, X86, Amd64) required by this module
    # ProcessorArchitecture = ''

    # Modules that must be imported into the global environment prior to importing this module
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    RequiredModules      = @('PSScriptAnalyzer')
========
    RequiredModules   = @(
        'Microsoft.Graph.Applications',
        'Az.Accounts',
        'Az.KeyVault'
    )
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

    # Assemblies that must be loaded prior to importing this module
    # RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    # ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    # TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    # FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    # NestedModules = @()

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport    = '*'

    # Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    CmdletsToExport      = '*'
========
    CmdletsToExport   = '*'
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

    # Variables to export from this module
    VariablesToExport    = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    AliasesToExport      = '*'
========
    AliasesToExport   = '*'
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

    # DSC resources to export from this module
    # DscResourcesToExport = @()

    # List of all modules packaged with this module
    # ModuleList = @()

    # List of all files packaged with this module
    # FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
    PrivateData          = @{
========
    PrivateData       = @{
>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags       = @('PSScriptAnalyzer')

            # A URL to the license for this module.
            LicenseUri = 'https://opensource.org/licenses/MIT'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/indented-automation/ScriptAnalyzerRules'

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

<<<<<<<< HEAD:tests/Indented.ScriptAnalyzerRules/Indented.ScriptAnalyzerRules.psd1
========
            # Prerelease string of this module
            # Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance for install/update/save
            # RequireLicenseAcceptance = $false

            # External dependent modules of this module
            ExternalModuleDependencies = @(
                'Microsoft.Graph.Applications',
                'Az.Accounts',
                'Az.KeyVault'
            )

>>>>>>>> 18d4dd8 (InitialVersion):InSpark.InfrastructureAsCode/InSpark.InfrastructureAsCode.psd1
        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    # HelpInfoURI = ''

    # Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
    # DefaultCommandPrefix = ''

}
