name: CI
on: [push, pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Test
        shell: pwsh
        run: ./build.ps1 -Task Test -Bootstrap

  SetLabels:
    name: Set labels
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        name: Set Label PRs
        if: github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: NathanielHill/check-pr-label-action@v4.0.0
        name: Check Label PRs
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          valid-labels: "patch, minor, major"
