name: Versioning
on: [pull_request]
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ github.ref }}"
      - id: semver-tag
        uses: gandarez/semver-action@v1.0.1
        with:
          main_branch_name: "main"
      - name: Test
        shell: pwsh
        run: |
          Update-ModuleManifest -ModuleVersion "${{ steps.semver-tag.outputs.semver_tag }}" -Path "${{ github.workspace }}/Module/Module.psd1"
